# PRODUCTION OVERRIDES

# The file that gets automatically merged into docker-compose.yml
# while running `docker-compose up -f docker-compose.prod.yml`.

version: "3.7"
services:
  app:
    env_file:
      - ./.env-prod
