# PRODUCTION OVERRIDES

# The file that gets automatically merged into docker-compose.yml
# while running `docker-compose up -f docker-compose.yml -f docker-compose.prod.yml`.

version: "3.7"
services:
  app:
    env_file:
      - ./.env-prod
    command: ["sh", "entrypoint-prod.sh"]
  db:
    env_file:
      - ./.env-prod
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
